server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 100m;

    resolver kube-dns.kube-system.svc.cluster.local valid=30s ipv6=off;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        # Strip /api/ prefix before proxying to rag-api
        rewrite ^/api/(.*) /$1 break;
        set $rag http://rag-api.ai-stack.svc.cluster.local:8000;
        proxy_pass         $rag;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        client_max_body_size 100m;
    }
}
