apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - ollama.yaml
  - openwebui.yaml
  - trywindeploy.yaml
  - trywinsvc.yaml
  - trywiningress.yaml
  - ptrywiningress.yaml
  - ingressai.yaml
  - ../RAG/manifests
