apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-stack

resources:
  - rag-pvc.yaml
  - rag-configmap.yaml
  - rag-deployment.yaml
  - rag-ingress.yaml
  - upload-ui.yaml
  - upload-ingress.yaml
