apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
  namespace: ai-stack
  labels:
    app: rag-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
      annotations:
        deploy-version: "8"
    spec:
      initContainers:
      - name: init-documents-dir
        image: busybox:stable
        command: ["sh", "-c", "mkdir -p /data/documents /data/chroma"]
        volumeMounts:
        - name: rag-data
          mountPath: /data

      containers:
      - name: rag-api
        image: pradyumnareddy/rag-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

        envFrom:
        - configMapRef:
            name: rag-config
        env:
        - name: OMP_NUM_THREADS
          value: "2"
        - name: MKL_NUM_THREADS
          value: "2"
        - name: ANONYMIZED_TELEMETRY
          value: "false"

        volumeMounts:
        - name: rag-data
          mountPath: /data

        resources:
          limits:
            memory: "600Mi"
            cpu: "500m"

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 60
          failureThreshold: 3

      volumes:
      - name: rag-data
        hostPath:
          path: /home/pradyumna/rag
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: rag-api
  namespace: ai-stack
spec:
  selector:
    app: rag-api
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
